### ISSUE TITLE
klientctl: move from codegangsta to cobra CLI

### ISSUE THREAD

**Issue by ppknap** [koding/koding#11278]
Requirements:

- [x] (#11277) Add `spf13/cobra` package to vendored ones.
- [x] (#11279) Unify common command operations and integrate them with cobra (logging, cache, metrics, admin checks, deamon requirement etc.).
- [x] (#11279) Create root command + `version` subcommand as a POC.
- [x] (#11306) Move `machine *` namespace to Cobra.
- [x] ~Move `compat *` namespace to Cobra(without extra refactoring since this is going to be removed)~
- [x] (#11306) Move `stack *`, `team *`, `template *` namespaces to Cobra.
- [x] (#11306) Move all remaining commands to cobra.
- [ ] Make Cobra CLI default.
- [ ] Drop `codegangsta/cli`

**Comment by rjeczalik** [comment]
I think we could drop `compat *` commands.

**Comment by ppknap** [comment]
> I think we could drop `compat *` commands.

Yeah, this would simplify the codebase since there is a tone of code which is used only by `compact` subcommands and a huge part of this code is UNIX only.
