### ISSUE TITLE
Gitlab Integration v0.1

### ISSUE THREAD

**Issue by tevirgen** [koding/koding#8160]
**Goals**
Bundle Koding with GitLab so we can reach more users easily

**Why we do?**
GitLab and Koding have same target audience which providing both services together makes sense.

**Acceptance Criteria**
- [x] Does Koding get installed with Gitlab?
- [x] Is 'Run This Project' working?
- [x] Did GitLab approve?

**Comment by ZJvandeWeg** [comment]
This issue probably needs an update.
