### ISSUE TITLE
Pricing Logic Implementation

### ISSUE THREAD

**Issue by usirin** [koding/koding#8467]
- [ ] Users will be segmented into 3 categories on signup process:
  1. Open Source Teams
  2. Individuals
  3. Teams/Organizations

- [ ] Users might have a different types of Free Trials depending upon which segment they belong to:
  - Open Source Users - Unlimited amount of free trial
  - Individuals: 7 days of free trial
  - Teams/Organizations: 30 days of free trial

- [ ] #8471 Different teams/organizations might have different period of free trials if they register as part of a promotional event.

- [ ] All team users will have limited access once a free trial expires.
  1. All VMs will stay in their current state (if it's an always-on machine, it will stay on.)
  2. No stacks can be run or edited.
  3. KD stops working.
  4. Users will only be able to see `Team Billing` on Dashboard.
    - All users will see a notification saying that their free trial has ended.
    - Admins will have the ability to enter a credit card.
    - Members will see an account suspended notification.
  5. Only way to reactivate an expired team is to enter a valid credit card, even if they have account credit.

- [ ] Once an admin enters a credit card, they got subscribed to the Koding. We have 1 type of subscription subscription:
  - Monthly
  - It starts from the day free trial ends.
  - Cost is calculated based upon how many members were part of the team in the past month. 
    - A member is defined as a user who joined the team for at least 24 hours.

- [ ] Initial subscription charge will be calculated for the current number of team members.

- [ ] There is 3 different pricing tiers based upon team member count:
  - Up to 10 users:  $49.97 per developer per month
  - Up to 50 users:  $39.97 per developer per month
  - Over 50 users:  $34.97 per developer per month

- [ ] Additional to standard pricing, for enterprise customers we will have the possibility to provide custom pricing. 
  - These will be negotiated in real life and might not match the standard pricing tiers.

- [ ] When a credit card gets declined:
  - All accounts connected to the team are immediately suspended.
  - The card will be auto-retried every 24 hours.
  - If a new valid card is entered, it will be attempted immediately.

- [ ] We will have a credit system where a dollar amount can be applied to a team for various actions. (e.g members can take a survey about their company, can refer to another paying customer)
  - This credit should be applied to team's next payment prior to the credit card charge.
  - Credit card validity should be checked before using the free credit.

- [ ] Koding admins should have a way to add free credit to any team.

- [ ] We need to implement `segment` events for each step of the process, as detailed as possible.

**Comment by usirin** [comment]
Outdated. Closing.
