### ISSUE TITLE
TODO for payment system

### ISSUE THREAD

**Issue by cihangir** [koding/koding#9098]
- [x] Manage due payments on invoice creation
- [x] Integrate new payment system into KD #8955
- [x] Integrate new payment system into kloud #8954
- [x] Clean up postgres from old payment system's artifacts
- [x] Log requests to swift science for fraud detection
##
