### ISSUE TITLE
KD.IO

### ISSUE THREAD

**Issue by davidsoul** [koding/koding#9501]
Initial spec (https://gist.github.com/usirin/99cb12ca112aae1b386b34b2b4d1f3c6)

CLI Feature Parity
- [x] [Credentials] #9502
- [x] Machines By Stack
- [ ] Stacks (wip @rjeczalik - https://github.com/koding/koding/issues/9569)
- [ ] Team List
- [ ] Team Invitations
- [ ] Signup

Template Hub (‘Stack & Stencil’)
- [ ] Front-end UI 
- [ ] Backend Github library

**Comment by davidsoul** [comment]
- [ ] 

Credentials (done)
Machines By Stack (done)
Stacks (Rafal experimental)
Team List
Team Invitations
Signup

**Comment by rjeczalik** [comment]
Superseded by https://github.com/koding/koding/projects/6.
