### ISSUE TITLE
kd.io: stacks backend

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9569]
- [x] kloud: backend for `kd credential list`
 - [x] kd: `credential list` subcommand
 - [x] kloud: backend for `kd credential create`
 - [x] kd: `credential create` subcommand
 - [ ] kd interactive mode for `credential create`
 - [ ] kloud: support for custom_\* credentials
 - [ ] kd: support custom_\* credentials with `credential create`
 - [x] kloud: backend for `kd stack create` (wip)
 - [x] kd: `stack create` subcommand (wip)
 - [ ] kloud: backend for `kd credential remove`
 - [ ] kd: `credential remove` subcommand
 - [ ] kloud: backend for `kd stack remove`
 - [ ] kd: `stack remove` subcommand

**Comment by rjeczalik** [comment]
Superseded by https://github.com/koding/koding/projects/6.
